# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16j3jGSwxWgZMknupf2i0T072egl-312v
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

iris_DS=pd.read_csv('IRIS.csv')

iris_DS

iris_DS.head(5)#shows the top 5 data

iris_DS.isnull().sum()#checks for the null value if any

"""Grouping of dataset according to the species"""

data=iris_DS.groupby("species") #grouping of data
data.head()

"""Types of species"""

iris_DS["species"].unique()

"""STEP 2: Data Visualization"""

plt.boxplot(iris_DS["sepal_length"])

plt.boxplot(iris_DS["sepal_width"])

sns.heatmap(iris_DS.corr())

"""STEP 3: Data Preperation"""

iris_DS["species"].replace({"Iris-setosa":1,"Iris-versicolor":2,"Iris-virginica":3},inplace=True)  #Transforming categorical data into Numerical data

iris_DS

"""Creating arrays for training and testing data


"""

x=pd.DataFrame(iris_DS,columns=["sepal_length","sepal_width","petal_length","petal_width"]).values

x

y=iris_DS.species.values.reshape(-1,1)

y

"""Importing libraries"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

"""Train Model"""

model=LinearRegression()

model.fit(x,y)

model.score(x,y)  #coefficient of prediction

model.intercept_

"""Making prediction

"""

y_pred=model.predict(x_test)

print("Total mean squared Error: %.2f" % np.mean((y_pred-y_test)**2))